apiVersion: v1
appVersion: "0.2"
home: https://github.com/prometheus/node_exporter/blob/master/text_collector_examples/smartmon.sh
description: Smart metrics exporter for prometheus
name: smart-exporter
version: 0.2.2
maintainers:
  - name: Bryan Alves
    email: bryanalves@gmail.com
