apiVersion: v1
kind: Service
metadata:
  name: {{ template "couchpotato.fullname" . }}
  labels:
    app: {{ template "couchpotato.name" . }}
    chart: {{ template "couchpotato.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: couchpotato
      protocol: TCP
      name: couchpotato
  selector:
    app: {{ template "couchpotato.name" . }}
    release: {{ .Release.Name }}
