apiVersion: v1
appVersion: "1.6.4"
home: https://mosquitto.org
description: Eclipse Mosquitto, MQTT broker
name: mosquitto
version: 0.0.1
maintainers:
  - name: Bryan Alves
    email: bryanalves@gmail.com
