apiVersion: v1
appVersion: "0.9.6"
home: https://github.com/rakshasa/rtorrent
description: A CLI/XMLRPC torrent client
name: rtorrent
version: 0.1.0
maintainers:
  - name: Bryan Alves
    email: bryanalves@gmail.com
