apiVersion: v1
appVersion: "2.2.0"
home: https://github.com/lovoo/ipmi_exporter
description: A prometheus exporter for IPMI
name: ipmi-exporter
version: 0.1.1
maintainers:
  - name: Bryan Alves
    email: bryanalves@gmail.com
