apiVersion: v1
appVersion: "0.0.1"
home: https://github.com/bryanalves/rtl_exporter
description: Export RTL-433 and RTLAMR data to mqtt and prometheus
name: rtl-exporter
version: 0.0.1
maintainers:
  - name: Bryan Alves
    email: bryanalves@gmail.com
