apiVersion: v1
kind: Service
metadata:
  name: {{ template "honeywell-exporter.fullname" . }}
  labels:
    app: {{ template "honeywell-exporter.name" . }}
    chart: {{ template "honeywell-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: {{ template "honeywell-exporter.name" . }}
    release: {{ .Release.Name }}
