apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "generic-web.fullname" . }}
  labels:
    app: {{ template "generic-web.name" . }}
    chart: {{ template "generic-web.chart" . }}
    release: {{ .Release.Name  }}
    heritage: {{ .Release.Service }}
{{- with .Values.config }}
data:
{{ toYaml . | indent 2 }}
{{- end }}
